import Head from 'next/head';
import React from 'react';
import CardList from '~/components/molecules/CardList';
import Layout from '~/components/molecules/Layout';
import type { CustomNextPage } from '~/types';

const dummyData = { title: 'test', imageUrl: 'https://t1.daumcdn.net/movie/0ec2fad5125dabb0400e455604dfdacd2df2b650' };
const fillDummyData = Array(15)
  .fill('')
  .map((v, i) => ({ ...dummyData, id: i + 1 }));

const Home: CustomNextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>hi</main>

      <CardList title="가로" size="small" videos={fillDummyData} />
      <CardList title="세로" size="medium" videos={fillDummyData} />
    </div>
  );
};

Home.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};

export default Home;
