import Head from 'next/head';
import React from 'react';
import Layout from '~/pages/components/molecules/Layout';
import type { CustomNextPage } from '~/types';

const Home: CustomNextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>hi</main>
    </div>
  );
};

Home.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};

export default Home;
